unit UnPRODUTOSTypes;

interface

type
  PRODUTOS = class
  const
    NomeTabela = 'PRODUTOS';

    ID = 'ID';
    CODIGO = 'CODIGO';
    DESCRICAO = 'DESCRICAO';
    VALOR_VENDA = 'VALOR_VENDA';
    VALOR_COMPRA = 'VALOR_COMPRA';
    QUANTIDADE = 'QUANTIDADE';
    IMAGEM = 'IMAGEM';
    CODIGO_BARRA = 'CODIGO_BARRA';
    DATACOMPRA = 'DATACOMPRA';
    UNIDADE = 'UNIDADE';
    CATEGORIA = 'CATEGORIA';
    MARCA = 'MARCA';
    LOCALIZACAO = 'LOCALIZACAO';
    LIMITEESTOQUE = 'LIMITEESTOQUE';
    OBSERVACOES = 'OBSERVACOES';
    PESOBRUTO = 'PESOBRUTO';
    PESOLIQUIDO = 'PESOLIQUIDO';
  end;

implementation

end.
